Accessibility Evaluation
Emmykage/portfolio pull request #8
Opened 2022-05-03 20:58 UTC by mikemtzp

## Accessibility Evaluation

For this feature we:

1. Evaluated the Accessibility of the portfolio project including the next points:

- [Page title](https://github.com/Emmykage/portfolio/blob/ee31d9e4c511b22e5f9512a82e49d082fe8ed826/index.html#L7) - Updated to a better page title "Portfolio - Morris Emeka"
- Image text alternatives - Updated `alt` attribute in [contact](https://github.com/Emmykage/portfolio/blob/ee31d9e4c511b22e5f9512a82e49d082fe8ed826/index.html#L28), [menu](https://github.com/Emmykage/portfolio/blob/ee31d9e4c511b22e5f9512a82e49d082fe8ed826/index.html#L32), [social media](https://github.com/Emmykage/portfolio/blob/ee31d9e4c511b22e5f9512a82e49d082fe8ed826/index.html#L52-L56), [background images](https://github.com/Emmykage/portfolio/blob/ee31d9e4c511b22e5f9512a82e49d082fe8ed826/index.html#L75) and [social media on the footer](https://github.com/Emmykage/portfolio/blob/ee31d9e4c511b22e5f9512a82e49d082fe8ed826/index.html#L232-L236)
- Text Headings - no issues found
- Color contrast - no issues found
- Resize - no issues found
- Interaction - no issues found
- Moving content - no issues found
- Multimedia - no issues found
- Basic structure of the page - no issues found

2. Updated the readme file.

2022-05-03 22:06 UTC, gtekle requested changes
Hi @Emmykage :wave: , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![dog-pug](https://user-images.githubusercontent.com/44057863/166573978-26950ea0-a04c-4fe1-8a0f-c35cb0b4a21a.gif)


## Highlights


## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly add labels to the form `input` and `textarea` elements for accessibility reasons.
- [ ] You should rectify the failing color contrast on the `see project` buttons and `language badges`. Please take a look at the following snapshot from `Aditus` - a tool you can use to check color contrast.
![button-color-contrast-fail](https://user-images.githubusercontent.com/44057863/166573886-ec899386-163f-4d95-8ac5-8379594ee909.png)
![language-badges-color-contrast-fail](https://user-images.githubusercontent.com/44057863/166573897-5e8470a6-c14a-4b8b-8202-68326dcda194.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-03 22:06 UTC, gtekle commented on index.html
> +                        <img src="image/Img_Placeholder.svg" alt=" ">
- [x] You should add `alt` text to the project snapshot image.

2022-05-03 22:06 UTC, gtekle commented on index.html
> +                        <h3><img src="image/bullets/Rectangle_55bullet.svg" alt=" ">Language</h3>
- [x] Kindly change the `<h1>` in the About me to `<h2>` so that heading hierarchy is meaningful. You should not have more than one `<h1>` tag in an HTML document - one of the reasons being accessibility.
`Ideally the page starts with an "h1" — which is usually similar to the page title — and does not skip levels.`
```
Example:
Heading Level 1 <h1>
  Heading Level 2 <h2>
     Heading Level 3 <h3>
     Heading Level 3 <h3>
  Heading Level 2 <h2>
     Heading Level 3 <h3>
        Heading Level 4 <h4>
        Heading Level 4 <h4>
  Heading Level 2 <h2>
```

2022-05-03 22:56 UTC, mikemtzp commented
Hello @gtekle!

Thank you very much for taking the time to give us a review!

For the label issue:
Is it necessary to put text inside of the `<label></label>l` tags? Or is it enough to just add the `label` with the `for` attribute matching the `id` attribute in the `input` element.

Example 1:
```
<label for="name">Name</label>
 <input name="name" id="name">
```
 
 Example 2:
 
```
<label for="name"></label>
 <input name="name" id="name">
```

Our doubt is which of the previous two scenarios is required for better accessibility, so a screen reader can detect it.

2022-05-03 23:21 UTC, gtekle commented
> Hello @gtekle!
> 
> Thank you very much for taking the time to give us a review!
> 
> For the label issue: Is it necessary to put text inside of the `<label></label>l` tags? Or is it enough to just add the `label` with the `for` attribute matching the `id` attribute in the `input` element.
> 
> Example 1:
> 
> ```
> <label for="name">Name</label>
>  <input name="name" id="name">
> ```
> 
> Example 2:
> 
> ```
> <label for="name"></label>
>  <input name="name" id="name">
> ```
> 
> Our doubt is which of the previous two scenarios is required for better accessibility, so a screen reader can detect it.

Hi @mikemtzp 
That is good question. I use the [wave](https://wave.webaim.org/) chrome plugin to check that part of accessibility.

2022-05-03 23:34 UTC, mikemtzp commented
> > Hello @gtekle!
> > Thank you very much for taking the time to give us a review!
> > For the label issue: Is it necessary to put text inside of the `<label></label>l` tags? Or is it enough to just add the `label` with the `for` attribute matching the `id` attribute in the `input` element.
> > Example 1:
> > ```
> > <label for="name">Name</label>
> >  <input name="name" id="name">
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Example 2:
> > ```
> > <label for="name"></label>
> >  <input name="name" id="name">
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Our doubt is which of the previous two scenarios is required for better accessibility, so a screen reader can detect it.
> 
> Hi @mikemtzp That is good question. I use the [wave](https://wave.webaim.org/) chrome plugin to check that part of accessibility.

I'll use the extension. Thanks a lot! 😁 @gtekle

2022-05-04 17:07 UTC, mikemtzp commented
Accessibility changes are done. All tests passed 💯 

Wave test:
![image](https://user-images.githubusercontent.com/97407840/166727055-0ee7cd35-f6a0-4c22-85a6-f1d71b72e642.png)

2022-05-04 17:15 UTC, ShadyShawkat approved these changes
## Hi @mikemtzp, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-04 17:27 UTC, merged